"""해석 작업 — simulations · simulation_artifacts (로드맵 1단계).

Revision ID: 0002_simulations
Revises: 0001_initial
Create Date: 2026-09-20 16:03:58.119105

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002_simulations"
down_revision: Union[str, Sequence[str], None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("recipe", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="queued", nullable=False),
        sa.Column(
            "spec",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "source_kind", sa.String(length=20), server_default="upload", nullable=False
        ),
        sa.Column("source_ref", sa.String(length=300), server_default="", nullable=False),
        sa.Column("input_sha256", sa.String(length=64), nullable=False),
        sa.Column("owner_workspace_id", sa.UUID(), nullable=True),
        sa.Column("requested_by_id", sa.UUID(), nullable=True),
        sa.Column("work_dir", sa.String(length=300), nullable=True),
        sa.Column(
            "stages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=40), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("worker_id", sa.String(length=80), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_simulations_owner_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
            name=op.f("fk_simulations_requested_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulations")),
    )
    op.create_index(
        op.f("ix_simulations_created_at"), "simulations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_simulations_deleted_at"), "simulations", ["deleted_at"], unique=False
    )
    op.create_index(
        op.f("ix_simulations_error_code"), "simulations", ["error_code"], unique=False
    )
    op.create_index(
        op.f("ix_simulations_input_sha256"), "simulations", ["input_sha256"], unique=False
    )
    op.create_index(
        op.f("ix_simulations_owner_workspace_id"),
        "simulations",
        ["owner_workspace_id"],
        unique=False,
    )
    op.create_index(op.f("ix_simulations_recipe"), "simulations", ["recipe"], unique=False)
    op.create_index(
        op.f("ix_simulations_requested_by_id"),
        "simulations",
        ["requested_by_id"],
        unique=False,
    )
    op.create_index(op.f("ix_simulations_status"), "simulations", ["status"], unique=False)
    op.create_table(
        "simulation_artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("simulation_id", sa.UUID(), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("relative_path", sa.String(length=300), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
            name=op.f("fk_simulation_artifacts_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_artifacts")),
    )
    op.create_index(
        op.f("ix_simulation_artifacts_created_at"),
        "simulation_artifacts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulation_artifacts_kind"), "simulation_artifacts", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_simulation_artifacts_simulation_id"),
        "simulation_artifacts",
        ["simulation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_simulation_artifacts_simulation_id"), table_name="simulation_artifacts"
    )
    op.drop_index(op.f("ix_simulation_artifacts_kind"), table_name="simulation_artifacts")
    op.drop_index(
        op.f("ix_simulation_artifacts_created_at"), table_name="simulation_artifacts"
    )
    op.drop_table("simulation_artifacts")
    op.drop_index(op.f("ix_simulations_status"), table_name="simulations")
    op.drop_index(op.f("ix_simulations_requested_by_id"), table_name="simulations")
    op.drop_index(op.f("ix_simulations_recipe"), table_name="simulations")
    op.drop_index(op.f("ix_simulations_owner_workspace_id"), table_name="simulations")
    op.drop_index(op.f("ix_simulations_input_sha256"), table_name="simulations")
    op.drop_index(op.f("ix_simulations_error_code"), table_name="simulations")
    op.drop_index(op.f("ix_simulations_deleted_at"), table_name="simulations")
    op.drop_index(op.f("ix_simulations_created_at"), table_name="simulations")
    op.drop_table("simulations")
    # ### end Alembic commands ###
