"""해석 작업의 출처 메타 — DOE 설계점(스터디 · 점 번호 · 바꾼 변수).

Revision ID: 0003_source_meta
Revises: 0002_simulations
Create Date: 2026-09-23 21:37:40.833167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003_source_meta"
down_revision: Union[str, Sequence[str], None] = "0002_simulations"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulations",
        sa.Column(
            "source_meta",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulations", "source_meta")
    # ### end Alembic commands ###
