"""작업 취소 — 워커가 다른 프로세스라 DB 칸으로만 알 수 있다.

Revision ID: 0004_cancel
Revises: 0003_source_meta
Create Date: 2026-09-24 00:26:10.349862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0004_cancel"
down_revision: Union[str, Sequence[str], None] = "0003_source_meta"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulations",
        sa.Column("cancel_requested_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulations", "cancel_requested_at")
    # ### end Alembic commands ###
