"""워커 신호 — 살아 있나 · 무엇을 집나 · 무엇이 깔렸나를 워커가 적는다(서버 화면).

Revision ID: 0005_workers
Revises: 0004_cancel
Create Date: 2026-10-03 18:37:41.431471

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0005_workers"
down_revision: Union[str, Sequence[str], None] = "0004_cancel"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_workers",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("hostname", sa.String(length=120), server_default="", nullable=False),
        sa.Column("pid", sa.Integer(), server_default="0", nullable=False),
        sa.Column("version", sa.String(length=40), server_default="", nullable=False),
        sa.Column("executor", sa.String(length=40), server_default="", nullable=False),
        sa.Column(
            "solvers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "tools",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("state", sa.String(length=20), server_default="idle", nullable=False),
        sa.Column("current_simulation_id", sa.UUID(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["current_simulation_id"],
            ["simulations.id"],
            name=op.f("fk_simulation_workers_current_simulation_id_simulations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_workers")),
    )
    op.create_index(
        op.f("ix_simulation_workers_last_seen_at"),
        "simulation_workers",
        ["last_seen_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_simulation_workers_last_seen_at"), table_name="simulation_workers")
    op.drop_table("simulation_workers")
    # ### end Alembic commands ###
