"""실측 — 센서 자리의 공진 · FRF · 변위 · 변형률을 작업이나 스터디에 붙인다.

Revision ID: 0006_measurements
Revises: 0005_workers
Create Date: 2026-10-03 18:54:26.989110

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0006_measurements"
down_revision: Union[str, Sequence[str], None] = "0005_workers"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_measurements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("simulation_id", sa.UUID(), nullable=True),
        sa.Column("study_id", sa.String(length=120), nullable=True),
        sa.Column("owner_workspace_id", sa.UUID(), nullable=True),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("original_name", sa.String(length=255), server_default="", nullable=False),
        sa.Column("rows", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_simulation_measurements_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_simulation_measurements_owner_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.id"],
            name=op.f("fk_simulation_measurements_simulation_id_simulations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_simulation_measurements")),
    )
    op.create_index(
        op.f("ix_simulation_measurements_created_at"),
        "simulation_measurements",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulation_measurements_deleted_at"),
        "simulation_measurements",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulation_measurements_owner_workspace_id"),
        "simulation_measurements",
        ["owner_workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulation_measurements_simulation_id"),
        "simulation_measurements",
        ["simulation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_simulation_measurements_study_id"),
        "simulation_measurements",
        ["study_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_simulation_measurements_study_id"), table_name="simulation_measurements"
    )
    op.drop_index(
        op.f("ix_simulation_measurements_simulation_id"), table_name="simulation_measurements"
    )
    op.drop_index(
        op.f("ix_simulation_measurements_owner_workspace_id"),
        table_name="simulation_measurements",
    )
    op.drop_index(
        op.f("ix_simulation_measurements_deleted_at"), table_name="simulation_measurements"
    )
    op.drop_index(
        op.f("ix_simulation_measurements_created_at"), table_name="simulation_measurements"
    )
    op.drop_table("simulation_measurements")
    # ### end Alembic commands ###
